name: Go Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/payment-service-go
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Build and Publish Docker Image
      run: |
        docker build -t $DOCKER_IMAGE_NAME .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push $DOCKER_IMAGE_NAME